name: Verificacao Automatica

on:
  push:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do projeto
        uses: actions/checkout@v4

      - name: Verificar arquivo
        run: test -f aula-actions.txt

      - name: Finalizar
        run: echo "Arquivo encontrado - verificacao concluida"
